services:
  - docker

install:
  - docker build -t jenkins_image .
  - docker run -d -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock --name jenkins jenkins_image

script:
  - docker ps | grep -q jenkins
